# Site settings
title: janus hasseriis
email: janus@hasseriis.net
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  /janushasseriis
url:  # the base hostname & protocol for your site
twitter_username: floede
github_username:  floede

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: false
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/
  articles:
    output: false
    permalink: /articles/:path/
